# Name of the workflow
name: build-push

# This workflow will run when there is a push (including merge) to the listed branches
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - v2.124
      - v2.122
      - v2.110
      - v2.87

# Jobs that will run when the workflow is triggered
jobs:
  # This job will build and then push to docker hub
  build-push:
    # The type of runner the job will run on
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write
      contents: read

    steps:
      # Checkout our Github repo
      - name: Checkout Github Repo
        uses: actions/checkout@v3

      # Upgrade Docker engine version, needed for building images.
      - name: Install Latest Docker Version
        run: |
          sudo apt-get purge docker-ce docker-ce-cli containerd.io runc containerd moby-buildx moby-cli moby-compose moby-containerd moby-engine moby-runc

          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

      # Setup Scala
      # Comes from open source action: https://github.com/coursier/setup-action
      - name: Setup Scala
        uses: coursier/setup-action@v1
        with:
          apps: sbt
          jvm: temurin:1.21

      # Authenticate GHCR to allow pushing to our alternate image registry
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}


      # Docker Build and Publish Local
      ## When creating docker image sbt will ~for some reason~ mark the logs as [error] when it should be [info]
      - name: Docker Build and Publish Local
        run: |
          sbt Docker/publishLocal

      - name: publish to local ghcr
        run: |
          docker image push ghcr.io/naphelps/am64_exchange-api:2.127.0-testing-0


